name: 'my first container action'
description: 'A cloud guru'
author: 'FarshadNick'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome Packops'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
